FROM amazoncorretto:17-alpine AS builder

WORKDIR /app

COPY . .
RUN chmod +x ./gradlew && ./gradlew clean build -x test

FROM amazoncorretto:17

WORKDIR /app

COPY --from=builder /app/build/libs/dagachi-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]